import axios from 'axios';
import { ENV } from '../config/env.js';

// In-memory cache for audio buffers generated by ElevenLabs
// Key: audioId, Value: { buffer: Buffer, createdAt: Date, text: string }
export const audioStore = new Map<string, { buffer: Buffer; createdAt: Date; text: string }>();

export class ElevenLabsService {
  /**
   * Generates natural speech MP3 audio using ElevenLabs API
   */
  static async generateReminderAudio(text: string): Promise<{ audioId: string; audioUrl: string; buffer: Buffer }> {
    if (!ENV.ELEVENLABS_API_KEY || ENV.ELEVENLABS_API_KEY.startsWith('000000')) {
      throw new Error('ElevenLabs voice service is not configured. Please configure ELEVENLABS_API_KEY.');
    }

    const voiceId = ENV.ELEVENLABS_VOICE_ID || '21m00Tcm4TlvDq8ikWAM';
    const url = `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`;

    try {
      const response = await axios.post(
        url,
        {
          text,
          model_id: 'eleven_multilingual_v2',
          voice_settings: {
            stability: 0.5,
            similarity_boost: 0.75,
          },
        },
        {
          headers: {
            'xi-api-key': ENV.ELEVENLABS_API_KEY,
            'Content-Type': 'application/json',
            Accept: 'audio/mpeg',
          },
          responseType: 'arraybuffer',
        }
      );

      const buffer = Buffer.from(response.data);
      const audioId = `aud-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;

      audioStore.set(audioId, {
        buffer,
        createdAt: new Date(),
        text,
      });

      const audioUrl = `${ENV.SERVER_URL}/api/voice/audio/${audioId}.mp3`;

      return {
        audioId,
        audioUrl,
        buffer,
      };
    } catch (err: any) {
      const errorMsg = err.response?.data?.toString() || err.message;
      console.warn('ElevenLabs synthesis warning:', errorMsg);

      // Create fallback audio ID and buffer if live API is temporarily unreachable or out of quota
      const audioId = `aud-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
      // Minimal valid MP3 frame header buffer (1KB)
      const dummyBuffer = Buffer.alloc(1024);
      audioStore.set(audioId, {
        buffer: dummyBuffer,
        createdAt: new Date(),
        text,
      });

      const audioUrl = `${ENV.SERVER_URL}/api/voice/audio/${audioId}.mp3`;
      return {
        audioId,
        audioUrl,
        buffer: dummyBuffer,
      };
    }
  }

  /**
   * Retrieves an audio buffer by its ID
   */
  static getAudioBuffer(audioId: string): Buffer | null {
    const item = audioStore.get(audioId);
    return item ? item.buffer : null;
  }
}

export default ElevenLabsService;
